"""Turn a handful of real HCI advertising reports into a C test fixture.

The expected values (event type, address type, RSSI, TX power, data length)
come from Wireshark's dissector via tshark, not from ble_hci.c. The C parser
is then tested against an independent decoder. A fixture built from the
parser's own output would only prove the parser agrees with itself.

Before anything is written to the repo, each event is scrubbed:
  * the address is replaced, keeping the two type bits of the MSB octet
  * name characters become 'x'
  * manufacturer and service-data payloads become 0x00, keeping company ID
    and service UUID
Lengths and structure are untouched, so the parser sees exactly the framing
the controller produced.

Usage: python3 extract_fixtures.py CAPTURE.pcapng > ../tests/fixtures.h
"""
import json
import subprocess
import sys

WANTED = [  # (label, tshark display filter)
    ("ADV_IND, public, flags + name",
     'btcommon.eir_ad.entry.type == 0x09 && bthci_evt.le_peer_address_type == 0'),
    ("SCAN_RSP, appearance + manufacturer",
     'btcommon.eir_ad.entry.type == 0x19 && btcommon.eir_ad.entry.type == 0xff'),
    ("flags + service data",
     'btcommon.eir_ad.entry.type == 0x16 && btcommon.eir_ad.entry.type == 0x01'),
    ("SCAN_RSP with no data",
     'bthci_evt.le_ext_advts_event_type == 0x001b && bthci_evt.data_length == 0'),
    ("Apple manufacturer data, random address",
     'btcommon.eir_ad.entry.company_id == 0x004c && bthci_evt.le_peer_address_type == 1'),
    ("ADV_NONCONN_IND",
     'bthci_evt.le_ext_advts_event_type == 0x0010'),
    ("flags + TX power AD + manufacturer",
     'btcommon.eir_ad.entry.type == 0x0a'),
]


USED = set()


def tshark_json(capture, flt):
    # -c counts packets *read*, not packets matched, so it cannot pick "the
    # first match". Find the frame number first, then fetch just that frame.
    nums = subprocess.run(
        ["tshark", "-r", capture, "-Y", f"bthci_evt.le_meta_subevent == 0x0d && ({flt})",
         "-T", "fields", "-e", "frame.number"],
        capture_output=True, text=True, check=True).stdout.split()
    nums = [n for n in nums if n not in USED]   # one frame per fixture, no repeats
    if not nums:
        return None
    USED.add(nums[0])
    out = subprocess.run(
        ["tshark", "-r", capture, "-Y", f"frame.number == {nums[0]}", "-T", "json", "-x"],
        capture_output=True, text=True, check=True).stdout
    return json.loads(out)[0]["_source"]["layers"]


def field(layer, name):
    v = layer[name]
    return v[0] if isinstance(v, list) else v


def scrub(ev):
    """ev: bytearray of one ext adv report event (starts at 0x3E)."""
    # addr at report offset 3..8, i.e. event offset 7..12; addr[5] is the MSB octet
    top = ev[12] & 0xC0
    fake = [0x11, 0x22, 0x33, 0x44, 0x55, 0x2A]
    ev[7:13] = bytes(fake[:5] + [top | fake[5]])
    dlen = ev[4 + 23]
    pos, end = 4 + 24, 4 + 24 + dlen
    while pos < end:
        flen = ev[pos]
        if flen == 0 or pos + 1 + flen > end:
            break
        t = ev[pos + 1]
        d0, d1 = pos + 2, pos + 1 + flen
        if t in (0x08, 0x09):                      # names
            ev[d0:d1] = b"x" * (d1 - d0)
        elif t == 0xFF:                            # keep 2-byte company ID
            ev[d0 + 2:d1] = bytes(max(0, d1 - d0 - 2))
        elif t == 0x16:                            # keep 2-byte service UUID
            ev[d0 + 2:d1] = bytes(max(0, d1 - d0 - 2))
        pos += 1 + flen
    return ev


def main():
    capture = sys.argv[1]
    rows = []
    for label, flt in WANTED:
        layers = tshark_json(capture, flt)
        if layers is None:
            print(f"/* no match for: {label} */", file=sys.stderr)
            continue
        raw = bytes.fromhex(field(layers, "bthci_evt_raw"))
        ev = layers["bthci_evt"]
        rows.append({
            "label": label,
            "bytes": scrub(bytearray(raw)),
            "evt_type": int(field(ev, "bthci_evt.le_ext_advts_event_type"), 16),
            "addr_type": int(field(ev, "bthci_evt.le_peer_address_type"), 0),
            "rssi": int(field(ev, "bthci_evt.rssi")),
            "tx_power": int(field(ev, "bthci_evt.tx_power")),
            "data_len": int(field(ev, "bthci_evt.data_length")),
        })

    print("/* Generated by tools/extract_fixtures.py from a real capture.")
    print(" * Controller: Intel AX201, host: BlueZ 5.72, extended scanning.")
    print(" * Expected values decoded by tshark. Addresses and payloads scrubbed. */")
    print("#ifndef FIXTURES_H\n#define FIXTURES_H\n\n#include <stddef.h>\n")
    print("typedef struct {\n    const char *label;\n    const unsigned char *bytes;\n"
          "    size_t len;\n    unsigned evt_type;\n    unsigned char addr_type;\n"
          "    signed char rssi;\n    signed char tx_power;\n    unsigned char data_len;\n"
          "} real_event_t;\n")
    for i, r in enumerate(rows):
        hexes = ", ".join(f"0x{b:02x}" for b in r["bytes"])
        print(f"/* {r['label']} */")
        print(f"static const unsigned char REAL_EVT_{i}[] = {{{hexes}}};\n")
    print("static const real_event_t REAL_EVENTS[] = {")
    for i, r in enumerate(rows):
        print(f'    {{"{r["label"]}", REAL_EVT_{i}, sizeof REAL_EVT_{i}, '
              f'0x{r["evt_type"]:04x}u, {r["addr_type"]}, {r["rssi"]}, '
              f'{r["tx_power"]}, {r["data_len"]}}},')
    print("};\n#define REAL_EVENT_COUNT (sizeof REAL_EVENTS / sizeof REAL_EVENTS[0])\n")
    print("#endif")


if __name__ == "__main__":
    main()
