#!/usr/bin/env python3
"""Turn chosen HCI ACL packets from a real connection into a C test fixture.

Like extract_fixtures.py for advertising reports: the raw bytes come from the
capture, and the expected values come from Wireshark's dissector via tshark,
not from ble_l2cap.c or ble_att.c — so the C parsers are tested against an
independent decoder, not against themselves.

The frames were picked by hand from a phone session against project 02 so
that none carries a name, an address, a key or a nonce: no SMP packets, no
reads of the phone's Device Name. The values in them are the laptop's
battery and temperature and the handles of project 02's GATT table.

Usage: python3 extract_acl_fixtures.py CAPTURE.pcapng > ../tests/acl_fixtures.h
"""
import json
import pathlib
import subprocess
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2] / "04-adv-privacy"))
from bleprivacy import monitor, pcapng  # noqa: E402

WANTED = [  # (frame, label)
    (41,  "LE signalling: Connection Parameter Update Request"),
    (42,  "ATT Exchange MTU Request, 517"),
    (50,  "ATT Exchange MTU Response, 517"),
    (48,  "ATT Read By Type Request, UUID16"),
    (62,  "ATT Read By Group Type Response: the service list"),
    (80,  "ATT Error Response: Attribute Not Found"),
    (117, "ATT Find Information Request"),
    (141, "ATT Write Response"),
    (371, "ATT Read Request: Battery Level"),
    (372, "ATT Read Response: 95 %"),
    (375, "ATT Read Response: temperature"),
    (377, "ATT Write Request: subscribe to Battery Level"),
    (380, "ATT Notification: Battery Level"),
    (385, "ATT Notification: temperature"),
    (401, "ATT Write Request: sample interval 50 ms"),
    (402, "ATT Error Response 0x80: interval refused"),
]


def first(layer, key, default=None):
    v = layer.get(key)
    if isinstance(v, list):
        v = v[0]
    return default if v is None else v


def expected(capture, frame):
    out = subprocess.run(["tshark", "-r", capture, "-Y", f"frame.number == {frame}",
                          "-T", "json", "-J", "bthci_acl btl2cap btatt"],
                         capture_output=True, text=True, check=True).stdout
    layers = json.loads(out)[0]["_source"]["layers"]
    acl, l2 = layers["bthci_acl"], layers["btl2cap"]
    att = layers.get("btatt", {})
    num = lambda layer, key, d=0: int(first(layer, key, str(d)), 0)
    return {
        "handle": num(acl, "bthci_acl.chandle"),
        "pb": num(acl, "bthci_acl.pb_flag"),
        "acl_len": num(acl, "bthci_acl.length"),
        "cid": num(l2, "btl2cap.cid"),
        "l2cap_len": num(l2, "btl2cap.length"),
        "att_opcode": num(att, "btatt.opcode", -1) if att else -1,
        # Wireshark lists several handles for list responses; only a PDU with
        # one Attribute Handle field has one to compare.
        "att_handle": num(att, "btatt.handle", 0) if att else 0,
        "err_code": num(att, "btatt.error_code", 0) if att else 0,
        "err_req": num(att, "btatt.req_opcode_in_error", 0) if att else 0,
        "mtu": num(att, "btatt.client_rx_mtu", num(att, "btatt.server_rx_mtu", 0)) if att else 0,
        "start": num(att, "btatt.starting_handle", 0) if att else 0,
        "end": num(att, "btatt.ending_handle", 0) if att else 0,
    }


def main(capture):
    raw = {}
    for p in pcapng.read_packets(capture):
        if p.frame in dict(WANTED):
            _, op, payload = monitor.split(p.data)
            assert op in (monitor.ACL_TX, monitor.ACL_RX), (p.frame, op)
            raw[p.frame] = (op, payload)

    print("/* Generated by tools/extract_acl_fixtures.py from a real connection between")
    print(" * an Android phone and project 02's peripheral (Intel AX201, BlueZ 5.72).")
    print(" * Expected values decoded by tshark. No SMP packet, name or address. */")
    print("#ifndef ACL_FIXTURES_H\n#define ACL_FIXTURES_H\n\n#include <stddef.h>\n")
    print("typedef struct {")
    print("    const char *label;\n    const unsigned char *bytes;\n    size_t len;")
    print("    int sent;            /* 1: laptop to phone (ACL_TX), 0: received */")
    print("    unsigned handle, pb, acl_len, cid, l2cap_len;")
    print("    int att_opcode;      /* -1: not an ATT PDU */")
    print("    unsigned att_handle, err_code, err_req, mtu, start, end;")
    print("} acl_fixture_t;\n")
    rows = []
    for i, (frame, label) in enumerate(WANTED):
        op, payload = raw[frame]
        e = expected(capture, frame)
        assert e["acl_len"] == len(payload) - 4, (frame, e, len(payload))
        name = f"ACL_FRAME_{frame}"
        print(f"/* frame {frame}: {label} */")
        print(f"static const unsigned char {name}[] = {{" +
              ", ".join(f"0x{b:02x}" for b in payload) + "};\n")
        rows.append(f'    {{"{label}", {name}, sizeof {name}, {int(op == monitor.ACL_TX)}, '
                    f'0x{e["handle"]:03x}u, {e["pb"]}u, {e["acl_len"]}u, 0x{e["cid"]:04x}u, '
                    f'{e["l2cap_len"]}u, {e["att_opcode"]}, 0x{e["att_handle"]:04x}u, '
                    f'0x{e["err_code"]:02x}u, 0x{e["err_req"]:02x}u, {e["mtu"]}u, '
                    f'0x{e["start"]:04x}u, 0x{e["end"]:04x}u}},')
    print("static const acl_fixture_t ACL_FIXTURES[] = {")
    print("\n".join(rows))
    print("};\n\n#endif /* ACL_FIXTURES_H */")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(sys.argv[1])
